spring.application.name=main

# URL de conex\u00e3o
spring.datasource.url=jdbc:postgresql://localhost:5432/RiffReview_db

# Usu\u00e1rio e senha padr\u00e3o do seu PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=Loathe

# Configura\u00e7\u00f5es do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto: 'update' cria ou atualiza as tabelas automaticamente com base nas suas Entidades
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado no console (\u00f3timo para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true