spring.application.name=main

# ===================================================================
# AMBIENTE ATIVO: SUPABASE (NUVEM)
# ===================================================================
spring.datasource.url=jdbc:postgresql://db.rcgwmgtxmnvfpfjfpqnx.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=B2XgfamRlhXDsN3I

# ===================================================================
# AMBIENTE DESATIVADO: LOCALHOST 
# ===================================================================
#spring.datasource.url=jdbc:postgresql://localhost:5432/RiffReview_db
#spring.datasource.username=postgres
#spring.datasource.password=Loathe


# ===================================================================
# CONFIGURA\u00c7\u00d5ES GERAIS DO HIBERNATE / JPA (Valem para os dois bancos)
# ===================================================================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto como update cria ou atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado formatado no console do NetBeans
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true