/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.musica.view;

//import br.com.ifba.album.view.*;
import br.com.ifba.musica.controller.MusicaIController;
import br.com.ifba.musica.entity.Musica;
import org.springframework.stereotype.Component;

/**
 *
 * @author Julia Freitas
 */
@Component
public class MusicaSave extends javax.swing.JFrame {
    
    private final MusicaIController musicaController;
    private Musica musicaEmEdicao; // Guarda a instância caso seja uma edição
    private Runnable aoSalvar;
    private javax.swing.JFrame telaAnterior;
    
    
    public void abrirTela(javax.swing.JFrame telaAnterior) {
    this.telaAnterior = telaAnterior;
    if (this.telaAnterior != null) {
        this.telaAnterior.setVisible(false); // Esconde a janela anterior
    }
    this.setLocationRelativeTo(null);
    this.setVisible(true);
}
    /**
     * Creates new form AlbumSave
     */
    public MusicaSave(MusicaIController musicaController) {
        this.musicaController = musicaController; 
        initComponents();
        
        spnDuracao.setEditor(new javax.swing.JSpinner.NumberEditor(spnDuracao, "#"));
    }

    public void setAoSalvar(Runnable aoSalvar) {
    this.aoSalvar = aoSalvar;
    }
    
    public void prepararEdicao(Musica musica) {
        this.musicaEmEdicao = musica;
        
        // Altera os textos da interface de forma dinâmica
        jLabel1.setText("EDITAR MÚSICA");
        btnSalvarMusica.setText("ATUALIZAR MÚSICA");
        
        // Preenche os campos com os dados existentes
        txtNome.setText(musica.getTitulo());
        txtGenero.setText(musica.getGeneroPrincipal());
        
        try {
            if (musica.getDuracao() != null) {
                spnDuracao.setValue(Integer.valueOf(musica.getDuracao()));
            }
        } catch (NumberFormatException e) {
            spnDuracao.setValue(0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnSalvarMusica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        spnDuracao = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalvarMusica.setBackground(new java.awt.Color(153, 255, 153));
        btnSalvarMusica.setText("SALVAR MUSICA");
        btnSalvarMusica.addActionListener(this::btnSalvarMusicaActionPerformed);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("ADICIONAR MUSICA");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Titulo:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setText("Duração:");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setText("Genero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(txtNome))
                            .addComponent(spnDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvarMusica)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvarMusica))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMusicaActionPerformed
       
        try {
        // 1. Validação dos campos
        if (txtNome.getText().trim().isEmpty() || txtGenero.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, preencha o Nome e o Gênero antes de salvar.", 
                    "Aviso", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }

        // 2. Determinar objeto
        Musica musicaParaSalvar = (this.musicaEmEdicao == null) ? new Musica() : this.musicaEmEdicao;
        
        musicaParaSalvar.setTitulo(txtNome.getText().trim());
        musicaParaSalvar.setGeneroPrincipal(txtGenero.getText().trim());
        musicaParaSalvar.setDuracao(String.valueOf(spnDuracao.getValue()));
        
        // 3. PERSISTÊNCIA CORRIGIDA (Chama save ou update baseado no estado)
        if (this.musicaEmEdicao == null) {
            this.musicaController.save(musicaParaSalvar);
        } else {
            this.musicaController.update(musicaParaSalvar); // Resolve o erro da imagem!
        }
        
        // 4. Feedback e Callback
        String acaoCompleta = (this.musicaEmEdicao == null) ? "salva" : "atualizada";
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Música '" + musicaParaSalvar.getTitulo() + "' " + acaoCompleta + " com sucesso!", 
                "Sucesso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Atualiza a tabela dinamicamente na tela pai
        if (this.aoSalvar != null) {
            this.aoSalvar.run(); 
        }
        
        // 5. Encerramento / Limpeza
        if (this.musicaEmEdicao != null) {
            this.dispose();
            if (this.telaAnterior != null) {
                this.telaAnterior.setVisible(true); // Restaura a tela da tabela
            }
        } else {
            limparCampos();
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Erro ao salvar a música: " + e.getMessage(), 
                "Erro no Sistema", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
        /*try {
            // 1. Validar se os campos obrigatórios não foram deixados em branco
            if (txtNome.getText().trim().isEmpty() || txtGenero.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Por favor, preencha o Nome e o Gênero antes de salvar.", 
                        "Aviso", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return; 
            }

            // 2. Determinar se cria uma nova instância ou usa a que está sendo editada (que já possui o ID)
            Musica musicaParaSalvar;
            if (this.musicaEmEdicao == null) {
                musicaParaSalvar = new Musica(); // Modo Cadastro
            } else {
                musicaParaSalvar = this.musicaEmEdicao; // Modo Edição
            }
            
            // Define os valores vindos dos campos da tela
            musicaParaSalvar.setTitulo(txtNome.getText().trim());
            musicaParaSalvar.setGeneroPrincipal(txtGenero.getText().trim());
            
            String duracaoStr = String.valueOf(spnDuracao.getValue());
            musicaParaSalvar.setDuracao(duracaoStr);
            
            // 3. Persistir os dados utilizando o Controller (O JPA faz update automaticamente se o ID existir)
            this.musicaController.save(musicaParaSalvar);
            
            // 4. Mensagem de sucesso dinâmica
            String acaoCompleta = (this.musicaEmEdicao == null) ? "salva" : "atualizada";
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Música '" + musicaParaSalvar.getTitulo() + "' " + acaoCompleta + " com sucesso!", 
                    "Sucesso", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            if (this.aoSalvar != null) {
            this.aoSalvar.run(); // Aciona o recarregamento da tabela!
            }
            
            // 5. Se for edição, fecha a janela para voltar à tabela. Se for cadastro, limpa a tela para a próxima.
            if (this.musicaEmEdicao != null) {
                this.dispose(); 
            } else {
                limparCampos();
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Erro ao salvar a música: " + e.getMessage(), 
                    "Erro no Sistema", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_btnSalvarMusicaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true); // Reexibe a janela pai ao voltar
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void limparCampos() {
        this.musicaEmEdicao = null; // Reseta o estado para modo cadastro
        jLabel1.setText("ADICIONAR MUSICA");
        btnSalvarMusica.setText("SALVAR MUSICA");
        txtNome.setText("");
        txtGenero.setText("");
        spnDuracao.setValue(0);  
        txtNome.requestFocus(); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar o visual Nimbus: " + ex.getMessage());
        }
        
        /* O gerenciamento do ciclo de vida das views agora é gerido exclusivamente pelo Spring Containers */
        // java.awt.EventQueue.invokeLater(() -> new MusicaSave().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarMusica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner spnDuracao;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
