/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.album.view;

import br.com.ifba.album.controller.AlbumIController;
import br.com.ifba.album.entity.Album;
import br.com.ifba.banda.controller.BandaIController;
import br.com.ifba.banda.entity.Banda;
import br.com.ifba.musica.controller.MusicaIController;
import br.com.ifba.musica.entity.Musica;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.stereotype.Component;

/**
 *
 * @author Julia Freitas
 */
@Component
public class AlbumSave extends javax.swing.JFrame {
    
    private final AlbumIController albumController;
    private final BandaIController bandaController;
    private final MusicaIController musicaController;
    
    // Atributo para controlar se a tela está em modo de edição ou inserção
    private Album albumEmEdicao = null;
    private List<Musica> musicasSelecionadas = new ArrayList<>();
    private DefaultTableModel tableModel;
    /**
     * Creates new form AlbumSave
     */
    public AlbumSave(AlbumIController albumController, BandaIController bandaController, MusicaIController musicaController) {
        this.albumController = albumController;
        this.bandaController = bandaController;
        this.musicaController = musicaController;
        
        initComponents();
        
        // Pega o modelo padrão da tabela criada no Design
        this.tableModel = (DefaultTableModel) tblMusicas.getModel();
        
        // Mantém a formatação do spinner do Ano limpa (sem o ponto de milhar)
        spinAno.setEditor(new javax.swing.JSpinner.NumberEditor(spinAno, "#"));
        
        // Carrega as bandas cadastradas no ComboBox logo ao abrir a tela
        carregarBandas();
    }

    // Método público chamado pela tela de listagem para injetar os dados em modo de edição
    public void preencherCampos(Album album) {
        if (album != null) {
            this.albumEmEdicao = album;
            
            // Altera o título visual da tela para guiar o usuário
            jLabel1.setText("EDITAR ALBUM");
            
            // Popula os componentes visuais básicos
            txtTitulo.setText(album.getNome());
            spinAno.setValue(album.getAnoLancamento());
            
            // Seleciona a banda correspondente no ComboBox baseado no ID (Protegido contra erro de Cast)
            if (album.getBanda() != null) {
                for (int i = 0; i < comboBanda.getItemCount(); i++) {
                    Object item = comboBanda.getItemAt(i);
                    if (item instanceof Banda) {
                        Banda b = (Banda) item;
                        if (b.getId() == (album.getBanda().getId())) {
                            comboBanda.setSelectedIndex(i);
                            break;
                        }
                    }
                }
            }
            
            // Clona ou atribui as músicas vinculadas ao álbum para a lista de manipulação da tabela
            if (album.getMusicas() != null) {
                this.musicasSelecionadas = new ArrayList<>(album.getMusicas());
            } else {
                this.musicasSelecionadas = new ArrayList<>();
            }
            
            atualizarTabelaMusicas();
        }
    }
    
    private void carregarBandas() {
        try {
            comboBanda.removeAllItems();
            List<Banda> bandas = bandaController.findAll();
            for (Banda b : bandas) {
                comboBanda.addItem(b);
            }
        } catch (Exception e) {
            System.out.println("Erro ao carregar as bandas no ComboBox: " + e.getMessage());
        }
    }

    // Método auxiliar para redesenhar a tabela sempre que a lista mudar
    private void atualizarTabelaMusicas() {
        tableModel.setRowCount(0); // Limpa as linhas atuais
        for (Musica m : musicasSelecionadas) {
            tableModel.addRow(new Object[]{m.getId(), m.getTitulo()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemoverMusica = new javax.swing.JButton();
        btnAdcionarMusica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBanda = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        spinAno = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusicas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnSalvarAlbum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRemoverMusica.setBackground(new java.awt.Color(255, 153, 153));
        btnRemoverMusica.setText("REMOVER MUSICA");
        btnRemoverMusica.addActionListener(this::btnRemoverMusicaActionPerformed);

        btnAdcionarMusica.setBackground(new java.awt.Color(153, 255, 153));
        btnAdcionarMusica.setText("ADCIONAR MUSICA");
        btnAdcionarMusica.addActionListener(this::btnAdcionarMusicaActionPerformed);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("ADICIONAR ALBUM");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Título:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Banda:");

        comboBanda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setText("Ano: ");

        tblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "NOME"
            }
        ));
        jScrollPane1.setViewportView(tblMusicas);

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalvarAlbum.setBackground(new java.awt.Color(153, 255, 153));
        btnSalvarAlbum.setText("SALVAR");
        btnSalvarAlbum.addActionListener(this::btnSalvarAlbumActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdcionarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemoverMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinAno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvarAlbum)))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverMusica)
                    .addComponent(btnAdcionarMusica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAlbum)
                    .addComponent(btnCancelar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdcionarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarMusicaActionPerformed
        try {
            // 1. Busca todas as músicas existentes cadastradas no sistema
            List<Musica> todasAsMusicas = musicaController.findAll();
            
            if (todasAsMusicas.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma música cadastrada no sistema para vincular.");
                return;
            }

            // 2. Prepara o array com os nomes para exibir no seletor
            String[] opcoes = new String[todasAsMusicas.size()];
            for (int i = 0; i < todasAsMusicas.size(); i++) {
                opcoes[i] = todasAsMusicas.get(i).getTitulo();
            }

            // 3. Abre uma caixinha de diálogo para escolha rápida
            String escolha = (String) javax.swing.JOptionPane.showInputDialog(
                    this, 
                    "Selecione a música para adicionar ao álbum:", 
                    "Adicionar Música Existente", 
                    javax.swing.JOptionPane.QUESTION_MESSAGE, 
                    null, 
                    opcoes, 
                    opcoes[0]
            );

            // 4. Procura o objeto correspondente e o adiciona se não for repetido
            if (escolha != null) {
                for (Musica m : todasAsMusicas) {
                    if (m.getTitulo().equals(escolha)) {
                        if (!musicasSelecionadas.contains(m)) {
                            musicasSelecionadas.add(m);
                            atualizarTabelaMusicas();
                        } else {
                            javax.swing.JOptionPane.showMessageDialog(this, "Esta música já foi adicionada ao álbum atual!");
                        }
                        break;
                    }
                }
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao buscar músicas: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAdcionarMusicaActionPerformed

    private void btnRemoverMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMusicaActionPerformed
        int linhaSelecionada = tblMusicas.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma música da tabela para removê-la.");
            return;
        }
        
        // Remove da lista pelo mesmo índice da tabela e renderiza novamente
        musicasSelecionadas.remove(linhaSelecionada);
        atualizarTabelaMusicas();
    }//GEN-LAST:event_btnRemoverMusicaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlbumActionPerformed
        try {
        // 1. Validação básica de campos textuais
        if (txtTitulo.getText().trim().isEmpty() || comboBanda.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, preencha o Título do Álbum e selecione uma Banda.", 
                    "Aviso", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Decide se cria um novo objeto ou se reaproveita o que está em edição (mantendo o ID)
        Album albumParaSalvar = (this.albumEmEdicao != null) ? this.albumEmEdicao : new Album();
        
        albumParaSalvar.setNome(txtTitulo.getText().trim());
        albumParaSalvar.setAnoLancamento((int) spinAno.getValue());
        albumParaSalvar.setBanda((Banda) comboBanda.getSelectedItem());
        
        // 3. Passa a lista temporária de músicas selecionadas para o Álbum
        albumParaSalvar.setMusicas(musicasSelecionadas);
        
        // 4. Atualiza o mapeamento bidirecional da JPA
        for (Musica m : musicasSelecionadas) {
            m.setAlbum(albumParaSalvar);
        }
        
        // 5. Salva ou atualiza o pacote completo no banco
        this.albumController.save(albumParaSalvar);
        
        //Mensagem dinâmica baseada na ação realizada
        String acao = (this.albumEmEdicao != null) ? "atualizado" : "salvo";
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Álbum '" + albumParaSalvar.getNome() + "' e suas faixas foram " + acao + "s com sucesso!", 
                "Sucesso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        limparCampos();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Erro ao salvar o álbum: " + e.getMessage(), 
                "Erro no Sistema", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSalvarAlbumActionPerformed

    private void limparCampos() {
        txtTitulo.setText("");
        spinAno.setValue(2026); 
        if (comboBanda.getItemCount() > 0) comboBanda.setSelectedIndex(0);
        musicasSelecionadas.clear();
        atualizarTabelaMusicas();
        
        // Reseta o estado da tela para o modo de inserção padrão
        this.albumEmEdicao = null;
        jLabel1.setText("ADICIONAR ALBUM");
        
        txtTitulo.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            System.out.println("Erro ao carregar o visual Nimbus: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdcionarMusica;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemoverMusica;
    private javax.swing.JButton btnSalvarAlbum;
    private javax.swing.JComboBox comboBanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinAno;
    private javax.swing.JTable tblMusicas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
