/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.banda.view;

import br.com.ifba.banda.controller.BandaIController;
import br.com.ifba.banda.entity.Banda;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Julia Freitas
 */
@Component
public class BandaSave extends javax.swing.JFrame {
    
    // TROCAMOS AQUI: Agora usamos o tipo da INTERFACE
    private final BandaIController bandaController;
    private Banda bandaEmEdicao = null; // Guarda a instância caso seja uma edição
    private javax.swing.JFrame telaAnterior;
    /**
     * Creates new form BandaSave
     */
    @Autowired
    public BandaSave(BandaIController bandaController) {
        this.bandaController = bandaController; 
        // O Spring injeta a implementação automaticamente
        initComponents();
        
        // Mantém a formatação do spinner sem o ponto
        spnAnoFormacao.setEditor(new javax.swing.JSpinner.NumberEditor(spnAnoFormacao, "#"));
    }

    public void abrirTela(javax.swing.JFrame telaAnterior) {
        this.telaAnterior = telaAnterior;
        if (this.telaAnterior != null) {
         this.telaAnterior.setVisible(false); // Esconde a janela anterior
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtGeneroPrincipal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnAnoFormacao = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalvar.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel1.setText("Nome:");

        txtNome.addActionListener(this::txtNomeActionPerformed);

        txtGeneroPrincipal.addActionListener(this::txtGeneroPrincipalActionPerformed);

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel4.setText("Ano de formação:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel5.setText("Genero:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel6.setText("ADICIONAR BANDA ");

        spnAnoFormacao.setModel(new javax.swing.SpinnerNumberModel(2026, 1500, 2026, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGeneroPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnAnoFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnSalvar)
                        .addGap(88, 88, 88)
                        .addComponent(btnCancelar)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGeneroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnAnoFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método público chamado pela tela de listagem para injetar os dados em modo de edição
    public void prepararEdicao(Banda banda) {
        this.bandaEmEdicao = banda;
        
        // Altera os textos da interface de forma dinâmica
        jLabel6.setText("EDITAR BANDA");
        btnSalvar.setText("ATUALIZAR");
        
        // Preenche os campos com os dados existentes
        txtNome.setText(banda.getNome());
        txtGeneroPrincipal.setText(banda.getGeneroPrincipal());
        spnAnoFormacao.setValue(banda.getAnoFormacao());
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // 1. Validar se os campos de texto não foram deixados em branco
            if (txtNome.getText().trim().isEmpty() || txtGeneroPrincipal.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Por favor, preencha o Nome e o Gênero antes de salvar.", 
                        "Aviso", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return; 
            }

            // 2. Determinar se cria uma nova instância ou usa a que está sendo editada (mantendo o ID)
            Banda bandaParaSalvar = (this.bandaEmEdicao != null) ? this.bandaEmEdicao : new Banda();
            
            bandaParaSalvar.setNome(txtNome.getText().trim());
            bandaParaSalvar.setGeneroPrincipal(txtGeneroPrincipal.getText().trim());
            
            int ano = (int) spnAnoFormacao.getValue();
            bandaParaSalvar.setAnoFormacao(ano);
            
            // 3. Chamar o Controller usando a Interface injetada pelo Spring
            this.bandaController.save(bandaParaSalvar);
            
            // 4. Mensagem de sucesso dinâmica
            String acaoCompleta = (this.bandaEmEdicao == null) ? "salva" : "atualizada";
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Banda '" + bandaParaSalvar.getNome() + "' " + acaoCompleta + " com sucesso!", 
                    "Sucesso", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // 5. Se for edição, fecha a janela. Se for cadastro, limpa a tela.
            if (this.bandaEmEdicao != null) {
                this.dispose(); 
            } else {
                limparCampos();
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Erro ao salvar a banda: " + e.getMessage(), 
                    "Erro no Sistema", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtGeneroPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroPrincipalActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true); // Reexibe a janela pai ao voltar
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void limparCampos() {
        this.bandaEmEdicao = null; // Reseta o estado para modo cadastro
        jLabel6.setText("ADICIONAR BANDA");
        btnSalvar.setText("SALVAR");
        txtNome.setText("");
        txtGeneroPrincipal.setText("");
        spnAnoFormacao.setValue(2026); 
        txtNome.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Pega os estilos visuais do Nimbus */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            // Se der erro no visual, ele só avisa no console sem travar o Maven
            System.out.println("Erro ao carregar o visual Nimbus: " + ex.getMessage());
        }

        /* Linha do Swing comentada pois quem gerencia agora é o Spring Boot */
        // java.awt.EventQueue.invokeLater(() -> new BandaSave().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner spnAnoFormacao;
    private javax.swing.JTextField txtGeneroPrincipal;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
