/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.avaliacao.view;

import br.com.ifba.album.controller.AlbumIController;
import br.com.ifba.album.entity.Album;
import br.com.ifba.avaliacao.controller.AvaliacaoIController;
import br.com.ifba.avaliacao.entity.Avaliacao;
import br.com.ifba.banda.controller.BandaIController;
import br.com.ifba.banda.entity.Banda;
import br.com.ifba.musica.controller.MusicaIController;
import br.com.ifba.musica.entity.Musica;
import br.com.ifba.usuario.entity.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.springframework.stereotype.Component;

/**
 *
 * @author Julia Freitas
 */

@Component
public class AvaliacaoViewSearch extends javax.swing.JFrame {
    
    private final BandaIController bandaController;
    private final AlbumIController albumController;
    private final MusicaIController musicaController;
    private final AvaliacaoIController avaliacaoController;
    
    private final AvaliacaoViewDetails avaliacaoViewDetails;
    
    private Usuario usuarioLogado = null;

    /**
     * Creates new form AvaliacaoSearchView
     */
    public AvaliacaoViewSearch(BandaIController bandaController,
                               AlbumIController albumController,
                               MusicaIController musicaController,
                               AvaliacaoIController avaliacaoController,
                               AvaliacaoViewDetails avaliacaoViewDetails) {
        
        this.bandaController = bandaController;
        this.albumController = albumController;
        this.musicaController = musicaController;
        this.avaliacaoController = avaliacaoController;
        this.avaliacaoViewDetails = avaliacaoViewDetails;
        
        initComponents();
        
        // Habilita listener para ativar o botão Detalhes ao selecionar uma linha da tabela
        tblResultados.getSelectionModel().addListSelectionListener(e -> {
            btnDetalhes.setEnabled(tblResultados.getSelectedRow() != -1);
        });
        
        btnDetalhes.addActionListener(this::btnDetalhesActionPerformed);
        
    }

    public void inicializarTela(Usuario usuario) {
        this.usuarioLogado = usuario;
        
        // Limpa campos anteriores ao abrir a tela
        txtPesquisa.setText("");
        btnGroupFiltro.clearSelection();
        
        DefaultTableModel tableModel = (DefaultTableModel) tblResultados.getModel();
        tableModel.setRowCount(0);
        
        btnDetalhes.setEnabled(false);
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFiltro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbBanda = new javax.swing.JRadioButton();
        rbMusica = new javax.swing.JRadioButton();
        rbAlbum = new javax.swing.JRadioButton();
        txtPesquisa = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("RiffReview -  Buscar  Avaliações");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar Por: ");

        btnGroupFiltro.add(rbBanda);
        rbBanda.setText("Banda");
        rbBanda.addActionListener(this::rbBandaActionPerformed);

        btnGroupFiltro.add(rbMusica);
        rbMusica.setText("Música");
        rbMusica.addActionListener(this::rbMusicaActionPerformed);

        btnGroupFiltro.add(rbAlbum);
        rbAlbum.setText("Álbum");
        rbAlbum.addActionListener(this::rbAlbumActionPerformed);

        txtPesquisa.setText("DIGITE O NOME DA BANDA/ÁLBUM/MÚSICA AQUI...");

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Genero"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        btnDetalhes.setText("DETALHES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(231, 231, 231))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(116, 116, 116)
                                .addComponent(rbBanda)
                                .addGap(125, 125, 125)
                                .addComponent(rbAlbum)
                                .addGap(115, 115, 115)
                                .addComponent(rbMusica))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDetalhes))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbBanda)
                    .addComponent(rbMusica)
                    .addComponent(rbAlbum))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnDetalhes))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBandaActionPerformed
        txtPesquisa.setText("");
    }//GEN-LAST:event_rbBandaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            DefaultTableModel tableModel = (DefaultTableModel) tblResultados.getModel();
            tableModel.setRowCount(0);
            
            String termoBusca = txtPesquisa.getText().trim();
            
            if (rbBanda.isSelected()) {
                // Adapte para o método real do seu controller (ex: findByNomeContaining ou findAll)
                List<Banda> bandas = this.bandaController.findAll(); 
                for (Banda b : bandas) {
                    if (b.getNome().toLowerCase().contains(termoBusca.toLowerCase())) {
                        tableModel.addRow(new Object[]{ b.getNome(), b.getGeneroPrincipal() });
                    }
                }
            } else if (rbAlbum.isSelected()) {
                List<Album> albuns = this.albumController.findAll();
                for (Album a : albuns) {
                    if (a.getNome().toLowerCase().contains(termoBusca.toLowerCase())) {
                        tableModel.addRow(new Object[]{ a.getNome(), a.getBanda() });
                    }
                }
            } else if (rbMusica.isSelected()) {
                List<Musica> musicas = this.musicaController.findAll();
                for (Musica m : musicas) {
                    if (m.getTitulo().toLowerCase().contains(termoBusca.toLowerCase())) {
                        tableModel.addRow(new Object[]{ m.getTitulo(), m.getGeneroPrincipal() });
                    }
                }
            } else {
                System.out.println("Nenhum filtro selecionado.");
            }
            
        } catch (Exception e) {
            System.out.println("Erro ao efetuar busca: " + e.getMessage());
            e.printStackTrace();
        }
    }                                         


    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {                                            
    /*int linhaSelecionada = tblResultados.getSelectedRow();
        if (linhaSelecionada != -1) {
            String nomeItem = tblResultados.getValueAt(linhaSelecionada, 0).toString();
        
            String tipoItem = "";
            if (rbBanda.isSelected()) tipoItem = "BANDA";
            else if (rbAlbum.isSelected()) tipoItem = "ALBUM";
            else if (rbMusica.isSelected()) tipoItem = "MUSICA";

            this.avaliacaoViewDetails.inicializarTela(nomeItem, tipoItem);
        }*/
    
    int linhaSelecionada = tblResultados.getSelectedRow();
    if (linhaSelecionada != -1) {
        String nomeItem = tblResultados.getValueAt(linhaSelecionada, 0).toString();
    
        String tipoItem = "";
        Long itemId = null;

        if (rbBanda.isSelected()) {
            tipoItem = "BANDA";
            List<Banda> bandas = this.bandaController.findAll();
            for (Banda b : bandas) {
                if (b.getNome().equalsIgnoreCase(nomeItem)) {
                    itemId = b.getId();
                    break;
                }
            }
        } else if (rbAlbum.isSelected()) {
            tipoItem = "ALBUM";
            List<Album> albuns = this.albumController.findAll();
            for (Album a : albuns) {
                if (a.getNome().equalsIgnoreCase(nomeItem)) {
                    itemId = a.getId();
                    break;
                }
            }
        } else if (rbMusica.isSelected()) {
            tipoItem = "MUSICA";
            List<Musica> musicas = this.musicaController.findAll();
            for (Musica m : musicas) {
                if (m.getTitulo().equalsIgnoreCase(nomeItem)) {
                    itemId = m.getId();
                    break;
                }
            }
        }

        if (itemId != null) {
            List<Avaliacao> avaliacoes = null;
            
            // Usa o método correto do controller com base no tipo do item selecionado
            if ("BANDA".equalsIgnoreCase(tipoItem)) {
                avaliacoes = (List<Avaliacao>) (List<?>) this.avaliacaoController.findByBandaId(itemId);
            } else if ("ALBUM".equalsIgnoreCase(tipoItem)) {
                avaliacoes = (List<Avaliacao>) (List<?>) this.avaliacaoController.findByAlbumId(itemId);
            } else if ("MUSICA".equalsIgnoreCase(tipoItem)) {
                avaliacoes = (List<Avaliacao>) (List<?>) this.avaliacaoController.findByMusicaId(itemId);
            }
            
            // Abre a tela de detalhes carregando os dados e a média corretamente
            this.avaliacaoViewDetails.carregarDetalhes(itemId, nomeItem, tipoItem, avaliacoes);
            this.avaliacaoViewDetails.setVisible(true);
        }
    }
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMusicaActionPerformed
        txtPesquisa.setText("");
    }//GEN-LAST:event_rbMusicaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void rbAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlbumActionPerformed
        txtPesquisa.setText("");
    }//GEN-LAST:event_rbAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        System.out.println("Erro ao carregar o visual Nimbus: " + ex.getMessage());
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.ButtonGroup btnGroupFiltro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAlbum;
    private javax.swing.JRadioButton rbBanda;
    private javax.swing.JRadioButton rbMusica;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
