/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.avaliacao.view;

import br.com.ifba.album.controller.AlbumIController;
import br.com.ifba.avaliacao.controller.AvaliacaoIController;
import br.com.ifba.avaliacao.entity.Avaliacao;
import br.com.ifba.banda.controller.BandaIController;
import br.com.ifba.musica.controller.MusicaIController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Julia Freitas
 */
@Component
public class AvaliacaoViewDetails extends javax.swing.JFrame {
    
    private final BandaIController bandaController;
    private final AlbumIController albumController;
    private final MusicaIController musicaController;

    @Autowired
    public AvaliacaoViewDetails(BandaIController bandaController, 
                                AlbumIController albumController, 
                                MusicaIController musicaController) {
        this.bandaController = bandaController;
        this.albumController = albumController;
        this.musicaController = musicaController;
        
        initComponents();
        
        // Ação do botão VOLTAR
        btnVoltar.addActionListener(e -> this.dispose());
    }

    public void carregarDetalhes(Long itemId, String nomeItem, String tipoItem, List<Avaliacao> avaliacoes) {
        lblItemSelecionado.setText(nomeItem);
        
        double media = 0.0;
        
        try {
            if (tipoItem != null) {
                switch (tipoItem.toUpperCase()) {
                    case "BANDA":
                        media = bandaController.calcularMediaAvaliacoes(itemId);
                        break;
                    case "ALBUM":
                    case "ÁLBUM":
                        media = albumController.calcularMediaNotas(itemId);
                        break;
                    case "MUSICA":
                    case "MÚSICA":
                        media = musicaController.calcularMediaNotas(itemId);
                        break;
                    default:
                        break;
                }
            }
            lblMediaGeral.setText(String.format("%.1f", media));
        } catch (RuntimeException e) {
            lblMediaGeral.setText("N/A");
            JOptionPane.showMessageDialog(this, 
                "Erro ao calcular a média: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }

        // Atualiza a tabela de avaliações dos usuários
        DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
        model.setRowCount(0); // Limpa as linhas anteriores

        if (avaliacoes != null) {
            for (Avaliacao av : avaliacoes) {
                model.addRow(new Object[]{
                    av.getUsuario() != null ? av.getUsuario().getNome() : "Anônimo",
                    av.getNota(),
                    av.getComentario() // Ajuste se a propriedade da mensagem/texto for diferente
                });
            }
        }
    }
    
    public void inicializarTela(String nomeItem, String tipoItem) {
        // 1. Define o texto do JLabel ou JTextField do "Item Selecionado"
        lblItemSelecionado.setText(nomeItem); 
        
        // 2. Limpa a tabela de avaliações dos usuários
        DefaultTableModel tableModel = (DefaultTableModel) tblResultados.getModel();
        tableModel.setRowCount(0);
        
        try {
            // 3. Busque as avaliações e a média usando seu avaliacaoController filtrando por nomeItem/tipoItem
            // Exemplo fictício de preenchimento da tabela:
            /*
            double media = avaliacaoController.calcularMedia(nomeItem, tipoItem);
            lblMediaGeral.setText(String.valueOf(media));
            
            List<Avaliacao> avaliacoes = avaliacaoController.findByItem(nomeItem, tipoItem);
            for (Avaliacao av : avaliacoes) {
                tableModel.addRow(new Object[]{ av.getUsuario().getNome(), av.getNota(), av.getComentario() });
            }
            */
            
            // Apenas para testes iniciais:
            lblMediaGeral.setText("4.5"); 
            tableModel.addRow(new Object[]{"Usuário Teste", "5", "Excelente trabalho!"});
            
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFiltro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        lblItemSelecionado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMediaGeral = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("RiffReview -  Detalhes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Item Selecionado: ");

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario", "Nota", "Avaliação Escrita"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        lblItemSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemSelecionado.setText("TEXT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Média Geral:");

        jLabel5.setText("★");

        lblMediaGeral.setText("MEDIA GERAL");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Avaliaçoes dos Usuários:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(286, 286, 286))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMediaGeral)
                            .addComponent(lblItemSelecionado)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVoltar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblItemSelecionado))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblMediaGeral))
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        System.out.println("Erro ao carregar o visual Nimbus: " + ex.getMessage());
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupFiltro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItemSelecionado;
    private javax.swing.JLabel lblMediaGeral;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables
}
