/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.avaliacao.view;

import br.com.ifba.avaliacao.controller.AvaliacaoController;
import br.com.ifba.avaliacao.entity.AvaliacaoAlbum;
import br.com.ifba.avaliacao.entity.AvaliacaoBanda;
import br.com.ifba.avaliacao.entity.AvaliacaoMusica;
import br.com.ifba.usuario.entity.Usuario;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
//import java.util.logging.Logger;
//import java.util.logging.Level;

/**
 *
 * @author Julia Freitas
 */

@Component
public class AvaliacaoSave extends javax.swing.JFrame {
    
    @Autowired
    private AvaliacaoController<AvaliacaoBanda> avaliacaoBandaController;

    @Autowired
    private AvaliacaoController<AvaliacaoAlbum> avaliacaoAlbumController;

    @Autowired
    private AvaliacaoController<AvaliacaoMusica> avaliacaoMusicaController;
    
    // Atributos para guardar o estado
    private Usuario usuarioLogado;
    private String contextoAtual;
    private java.util.List<?> listaDeItensOriginais;
    
    //tela anterior
    private javax.swing.JFrame telaAnterior;
    /**
     * Creates new form AvaliacaoSave
     */
    public AvaliacaoSave() {
        initComponents();
    }

    public void abrirTela(javax.swing.JFrame telaAnterior) {
    this.telaAnterior = telaAnterior;
        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(false);
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void inicializarTela(Usuario usuario, String contexto, java.util.List<?> itens) {
        
        System.out.println("DEBUG - Usuário recebido no AvaliacaoSave: " + usuario);
        
        this.usuarioLogado = usuario;
        this.contextoAtual = contexto;
        this.listaDeItensOriginais = itens; // Armazena a lista recebida
        
        lblEscolha.setText("Escolha a " + contexto.toLowerCase() + ": ");
        cbxItemAvaliado.removeAllItems();
        
        for (Object item : itens) {
            if ("BANDA".equals(contexto)) {
                br.com.ifba.banda.entity.Banda banda = (br.com.ifba.banda.entity.Banda) item;
                cbxItemAvaliado.addItem(banda.getNome());
            } else if ("ALBUM".equals(contexto)) {
                br.com.ifba.album.entity.Album album = (br.com.ifba.album.entity.Album) item;
                cbxItemAvaliado.addItem(album.getNome()); 
            } else if ("MUSICA".equals(contexto)) {
                br.com.ifba.musica.entity.Musica musica = (br.com.ifba.musica.entity.Musica) item;
                cbxItemAvaliado.addItem(musica.getTitulo());
            }
        }
        
        // Limpa os campos de texto e spinner para novas inserções
        txtComentario.setText("");
        spnNota.setValue(0);
        
        //this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        spnNota = new javax.swing.JSpinner();
        cbxItemAvaliado = new javax.swing.JComboBox<>();
        lblEscolha = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("Avaliação");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nota: ");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setText("Comentário:");

        txtComentario.setColumns(20);
        txtComentario.setLineWrap(true);
        txtComentario.setRows(5);
        txtComentario.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtComentario);

        spnNota.setModel(new javax.swing.SpinnerNumberModel(0.0, 0.0, 5.0, 0.5));

        cbxItemAvaliado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEscolha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEscolha.setText("Escolha: ");

        btnCancelar.setText("SAIR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSalvar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(spnNota, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEscolha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxItemAvaliado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxItemAvaliado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEscolha))
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int indexSelecionado = cbxItemAvaliado.getSelectedIndex();

        if (indexSelecionado == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um item para avaliar.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double nota = ((Number) spnNota.getValue()).doubleValue();
        String comentario = txtComentario.getText();
        Object itemEscolhido = listaDeItensOriginais.get(indexSelecionado);

        try {
            if ("BANDA".equals(contextoAtual)) {
                AvaliacaoBanda novaAvaliacao = new AvaliacaoBanda();
                novaAvaliacao.setUsuario(this.usuarioLogado);
                novaAvaliacao.setNota(nota);
                novaAvaliacao.setComentario(comentario);
                novaAvaliacao.setDataCriacao(LocalDateTime.now());
                novaAvaliacao.setBandaAvaliada((br.com.ifba.banda.entity.Banda) itemEscolhido);

                // Salva utilizando o controller específico de Banda
                avaliacaoBandaController.save(novaAvaliacao);

            } else if ("ALBUM".equals(contextoAtual)) {
                AvaliacaoAlbum novaAvaliacao = new AvaliacaoAlbum();
                novaAvaliacao.setUsuario(this.usuarioLogado);
                novaAvaliacao.setNota(nota);
                novaAvaliacao.setComentario(comentario);
                novaAvaliacao.setDataCriacao(LocalDateTime.now());
                novaAvaliacao.setAlbumAvaliado((br.com.ifba.album.entity.Album) itemEscolhido);

                // Salva utilizando o controller específico de Album
                avaliacaoAlbumController.save(novaAvaliacao);

            } else if ("MUSICA".equals(contextoAtual)) {
                AvaliacaoMusica novaAvaliacao = new AvaliacaoMusica();
                novaAvaliacao.setUsuario(this.usuarioLogado);
                novaAvaliacao.setNota(nota);
                novaAvaliacao.setComentario(comentario);
                novaAvaliacao.setDataCriacao(LocalDateTime.now());
                novaAvaliacao.setMusicaAvaliada((br.com.ifba.musica.entity.Musica) itemEscolhido);

                // Salva utilizando o controller específico de Musica
                avaliacaoMusicaController.save(novaAvaliacao);
            }

            /*JOptionPane.showMessageDialog(this, "Avaliação salva com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            if (this.telaAnterior != null) {
                this.telaAnterior.setVisible(true); // Faz a tela pai/menu reaparecer ao voltar
            }*/
            
            /*JOptionPane.showMessageDialog(
            this,
            "Avaliação salva com sucesso!",
            "Sucesso",
           JOptionPane.INFORMATION_MESSAGE
        );

        // Atualiza a tabela da tela principal
        if (this.telaAnterior instanceof AvaliacaoView) {

        AvaliacaoView tela = (AvaliacaoView) this.telaAnterior;

        tela.carregarAvaliacoesDoUsuario();

        tela.setVisible(true);   
    }*/
            
            JOptionPane.showMessageDialog(
            this,
            "Avaliação salva com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );

            // Atualiza a tabela da tela anterior
            if (this.telaAnterior instanceof AvaliacaoView) {

                ((AvaliacaoView) this.telaAnterior).atualizarTabela();

            } else if (this.telaAnterior instanceof AvaliacaoViewAdm) {

            ((AvaliacaoViewAdm) this.telaAnterior).atualizarTabela();
        }

        this.dispose();
        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true); // Faz a tela pai/menu reaparecer ao voltar
        }

        } catch (Exception e) {
            System.err.println("Erro ao salvar a avaliação: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao tentar salvar avaliação no banco de dados: " + e.getMessage(), "Erro Interno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        if (this.telaAnterior != null) {
            this.telaAnterior.setVisible(true); // Faz a tela pai/menu reaparecer ao voltar
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        System.out.println("Erro ao carregar o visual Nimbus: " + ex.getMessage());
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Object> cbxItemAvaliado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEscolha;
    private javax.swing.JSpinner spnNota;
    private javax.swing.JTextArea txtComentario;
    // End of variables declaration//GEN-END:variables
}
